<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Bewit.Http</RootNamespace>
    <AssemblyName>Bewit.Http</AssemblyName>
    <PackageId>Bewit.Http</PackageId>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\Validation\Validation.csproj"/>
    <ProjectReference Include="..\Core\Core.csproj"/>
  </ItemGroup>

</Project>
