using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("Bewit.Generation")]
[assembly: InternalsVisibleTo("Bewit.Validation")]
[assembly: InternalsVisibleTo("Bewit.Storage.MongoDB")]
[assembly: InternalsVisibleTo("Bewit.Extensions.HotChocolate")]
[assembly: InternalsVisibleTo("Bewit.Extensions.Mvc")]
[assembly: InternalsVisibleTo("Bewit.Http")]
[assembly: InternalsVisibleTo("Bewit.Tests")]
[assembly: InternalsVisibleTo("Bewit.Generation.Tests")]
[assembly: InternalsVisibleTo("Bewit.Validation.Tests")]
[assembly: InternalsVisibleTo("Bewit.Storage.MongoDB.Tests")]
[assembly: InternalsVisibleTo("Bewit.Extensions.HotChocolate.Tests")]
[assembly: InternalsVisibleTo("Bewit.Extensions.Mvc.Tests")]
[assembly: InternalsVisibleTo("Bewit.Http.Tests")]
[assembly: InternalsVisibleTo("DynamicProxyGenAssembly2")]
