<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Bewit.Storage.MongoDB</RootNamespace>
    <AssemblyName>Bewit.Storage.MongoDB</AssemblyName>
    <PackageId>Bewit.Storage.MongoDB</PackageId>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\Core\Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" />
    <PackageReference Include="MongoDB.Driver" />
  </ItemGroup>

</Project>
