<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>Bewit.Validation.Tests</AssemblyName>
    <RootNamespace>Bewit.Validation.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Validation\Validation.csproj" />
    <ProjectReference Include="..\..\src\Generation\Generation.csproj" />
    <ProjectReference Include="..\..\src\Core\Core.csproj" />
  </ItemGroup>

</Project>
