<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Bewit.IntegrationTests</AssemblyName>
    <RootNamespace>Bewit.IntegrationTests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Core\Core.csproj" />
    <ProjectReference Include="..\..\src\Storage.MongoDB\Storage.MongoDB.csproj" />
    <ProjectReference Include="..\..\src\Compatibility.V8\Compatibility.V8.csproj" />
    <ProjectReference Include="..\..\src\Compatibility.V8.MongoDB\Compatibility.V8.MongoDB.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Squadron.Mongo" />
  </ItemGroup>
</Project>
